### ISSUE TITLE
Update the pypi package!

### ISSUE THREAD

**Issue by CodeCubeNeo** [greg-hellings/dnszone#8]
PLS URGENT !!!!!

**Comment by greg-hellings** [comment]
Don't know why it would be urgent, as this is not a project that I work on any longer and have never pushed to anyone else. But I have made a v3.1.1 release on PyPI. It contains no major code changes besides moving all the metadata to pyproject.toml instead of splitting it between pyproject.toml/setup.cfg/setup.py and raising the minimum Python version to 3.8.

**Comment by CodeCubeNeo** [comment]
Yes, i am sorry that i wrote urgent, i just need it asap for my project (just wanted to speed things up - i guess it helped ;). Anyways: truly thank you.
